@local = http://localhost:8080

GET {{local}}/task
###

POST {{local}}/task
content-type: application/json

{
    "name": "sample",
    "task": "Wed, 21 Oct 2015 18:27:50 GMT:Warning: ",
    "usuario": null
}

###
DELETE {{local}}/task/234

###
PUT {{local}}/task/2738
content-type: application/json

{
    "name": "sample",
    "task": "Wed, 21 Oct 2015 18:27:50 GMT:Warning: ",
    "usuario": null
}


