@local = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjYwZDJhNDkwMTg0YzUwMjQyNWNlNDM4MiIsIm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIiLCJfX3YiOjB9LCJpYXQiOjE2MjQ1ODM2NDYsImV4cCI6MTYyNDU5MzcyNn0.yEozOcT8unxl0hD5N7-NhTZYaVGRSLTJQxKy16RG7l0 

POST {{local}}/user
content-type: application/json

{
    "name": "example",
    "email": "example@example.com",
    "pass1": "11223344",
    "pass2": "11223344"
}

###
POST {{local}}/login
content-type: application/json

{
    "email": "example@example.com",
    "password": "11223344"
}

###
GET {{local}}/user/auth
token: {{token}}